EXT : '001'
TRAINING : True
USE_FINETUNE : True     
FOLDS : 5
GROUP_GAP : 31
SEED : 66
INPUTPATH : ../../input
NUM_EPOCH : 300
BATCH_SIZE : 16384
PATIANCE : 20
LR : 0.0005
MDL_PATH  :  ../models
MDL_NAME : autoencoder
VER : cv_base
THRESHOLD : 0.5